### ISSUE TITLE
Bridge can receive `callData` for `proxyCall()` with address bytes in reversed order

### ISSUE THREAD

**Issue by rvnlord** [O3Labs/o3swap-v2-core#20]
There is a serious bug I encountered while swapping assets from Neo3 --> Arbitrum, I assessed that it is not exploitable but it leads to bridged assets being sent into the address with an unknown private key.

The issue originates in `bridgeIn()` function of `Bridge.sol` contract, `argsBs` received from poly network and further deserialized by `_deserializeTxArgs()` and then by `decodeCallDataForExternalCall()` of `CallProxy.sol` can receive correct (receiver) address while receiving the same address as part of `callData` encoded in incorrect endian (in reversed bytes order). This `callData` is then passed into `exactInputSinglePToken(`) of `O3ArbitrumUniswapV3Aggregator` as part of the proxy call (`proxyCall` visits `else if (externalCallEnabled && tag == 0x03)`) resulting in lost funds.

Since I am not sure how how much control you have over the poly network code, my proposed solution is to modify the Arbitrum contracts to check and correct the `callData` before passing it to the Uniswap aggregator.

I propose adding the following function into `Bridge.sol` contract:

```
function fixAddressEndianness(bytes memory callData, bytes memory toAddress) public pure returns (bytes memory) {
    bytes memory reversedAddress = Utils.reverseBytes(toAddress);
    if (Utils.indexOf(callData, reversedAddress) > -1) {
        return Utils.replaceBytes(callData, reversedAddress, toAddress);
    }

    return callData;
}
```

and modifying `_deserializeTxArgs()` to include the endianness check:

```
function _deserializeTxArgs(bytes memory valueBs) public pure returns (TxArgs memory) {
    TxArgs memory args;
    uint256 off = 0;
    (args.toAssetHash, off) = Utils.NextVarBytes(valueBs, off);
    (args.toAddress, off) = Utils.NextVarBytes(valueBs, off);
    (args.amount, off) = Utils.NextUint255(valueBs, off);
    (args.callData, off) = Utils.NextVarBytes(valueBs, off);
    args.callData = fixAddressEndianness(args.callData, args.toAddress);
    return args;
}
```

I also placed 3 additional ultility functions within your `Utils.sol` library:

```
function reverseBytes(bytes memory data) internal pure returns (bytes memory) {
    bytes memory reversed = new bytes(data.length);
    for (uint256 i = 0; i < data.length; i++) {
        reversed[i] = data[data.length - 1 - i];
    }
    return reversed;
}

function indexOf(bytes memory data, bytes memory subData) internal pure returns (int256) {
    if (data.length < subData.length) {
        return -1;
    }
    if (subData.length == 0) {
        return 0;
    }

    for (uint256 i = 0; i <= data.length - subData.length; i++) {
        bool found = true;
        for (uint256 j = 0; j < subData.length; j++) {
            if (data[i + j] != subData[j]) {
                found = false;
                break;
            }
        }
        if (found) {
            return int256(i);
        }
    }

    return -1;
}

function replaceBytes(bytes memory data, bytes memory oldData, bytes memory newData) internal pure returns (bytes memory) {
    int256 index = indexOf(data, oldData);
    require(index >= 0, "Old data not found in bytes");

    bytes memory replaced = new bytes(data.length - oldData.length + newData.length);
    uint256 j;

    for (uint256 i = 0; i < uint256(index); i++) {
        replaced[j++] = data[i];
    }

    for (uint256 i = 0; i < newData.length; i++) {
        replaced[j++] = newData[i];
    }

    for (uint256 i = uint256(index) + oldData.length; i < data.length; i++) {
        replaced[j++] = data[i];
    }

    return replaced;
}
```

I have provided the details, including the actual function arguments of my call, in the discord support ticket (I am not going to publish them for obvious reasons), you don't need them to test the fix for this issue though, you can just use any arguments and replace the address with a reversed one in `callData` for this purpose (for when poly network sends an incorrect one).

You have two choices, you can basically account for the possible incorrect endian in the receiving contract and modify the deserializer as I showed here or you can modify the serializer of the poly network.

**Comment by rickcain** [comment]
Hi, thanks for the report.

We've carefully read your content, it is a pretty nice double check logic from your perspective, we've considered that check before, but actually we didn't apply that specific check for reasons:

First, there are two address variables, `toAddress` directly from `argsBs`, and `receiver` from `callData`, these two addresses is allowed to be different, `callData` is open to user to do some customized logic on destination chain, for example, a very common usage is users can swaps **all** the received destination chain tokens for another token / native asset, or they could choose to swap part of the tokens to some addresses, and keep the rest tokens to the `toAddress`, all of these actions is controlled by users themselves.

Second, suppose we have to consider big/little endian from contract code layer, then these two addresses mentioned above will all be involved, that means there are different scenarios should be taken in to account:

without callData:
* `toAddress` is in right encoding: succeed
* `toAddress` is in wrong encoding: failed

with callData:
* `toAddress` is right, `receiver` is right: succeed
* `toAddress` is right, `receiver` is wrong: failed
* `toAddress` is wrong, `receiver` is right: succeed in most cases(aggregator will send all tokens to `receiver`)
* `toAddress` is wrong, `receiver` is wrong: failed

So you can see the main reason is these two addresses are not strictly equal, it depends on the input on source chain, and the equality check does not help solving the input issue.

third, the callData is totally customized, sometimes it can be long bytes, it is not possible to unpack the data back to variables, so in order to apply the check,  the only way is to do double layer for loop check, though it is very less likely, but you cannot tell if there are unrelated bytes accidentally match the search pattern. From another perspective, `Bridge` or `CallProxy` should not modify any content of the `callData`, it is not what they should do, that's why the external call is designed to be processed if data is legal, or allowed to be reverted if the call failed.

If the cross-chain pattern itself is strict or limited, the check should and must be applied, but in an opening pattern, it is nearly impossible to check if user provided addresses are correct or not. There are still many things can be done to prevent the reverse issue, such as add more unit tests, tests more on testnets, and so on. That's what we've done or doing.

Thanks for your time, your code are complete and beautiful.

I'm going to close this issue, if you have more to discuss, feel free to reopen this issue.

**Comment by rvnlord** [comment]
While as we established it is better to solve it before it reaches the contract layer, be aware that this was only an example solution, it wasn't meant to solve all cases, especially since there is no public info about how exactly your stack looks like. 

As for the 1st clarification: I used `toAddress` as a "guard" value because in my tests with limited knowledge it was never sent in reversed order. 

As for the 2nd and 3rd clarification - I can come up with the solution accounting for that if you need me to. it is very unlikely that sth random would match a reversed `receiver` or `toAddress` by accident (random collision with inverted hash?). Even in a call within a call within a call, it would just be incorrectly encoded address.

Since you don't want to modify the `callData`, It is actually more simple than you think, just revert the call when unpacking and encountering the inverted address. You can check if address is inverted by calculating its checksum. You basically make the check only after you are sure the parameter should be an address.

Since you solved this problem by correcting the configuration of your "web end" but didn't clarify if you meant poly network node, reverse proxy or something else It is difficult to assess where is the best place to safeguard against this kind of issue and if it was indeed fixed (even purely from a user perspective). Especially not knowing how your stack works together.

The problem is that anyone can apply to become a poly network relayer and run a full node, so consequently anyone can potentially make such misconfiguration as far as I understand it, so don't contracts have to ultimately account for it?

**Comment by rickcain** [comment]
We understand you do not have much knowledge about the poly network, poly relayers can only "pass" data from one chain to another, any data modification will be invalid(it's obvious, otherwise if relayers have the ability to compose arbitrary fake data, then then whole protocol would crash immediately). What the source chain tx provides, what the destination chain receives, so the key is to ensure the data provided is valid, and passed all the contract verification mechanisms, before being confirmed by the source chain.

Also, as I said, it is very unlikely the collision would happen, the second reason above is to say, if we consider some addresses would be incorrect when composing the callData, then the possibility to accidentally paste a 'wrong' `toAddress` can be the same, you cannot assume the first address, the `toAddress` from `argBs` is forever correct. Check the cases listed in my previous post, 3 succeed 1 failed if check not applied, 3 succeed 1 failed if check applied, with higher gas cost. If the address equality check is applied, it means a different 'limitation': "if we search bytes and find a matched pattern, then we will modify data provided by you, otherwise we will revert the call, if revert happened in bridge, then the destination chain tx will never be confirmed cause the tx data is unchangeable, if revert happened in the callproxy, then the user will receive all the ptokens(if the `toAddress` **is correctly provided**)". 

If there are only evm compatible chains, then the check is fine to be added(regardless of other factors), we can assume the `toAddress` as a guard, but with heterogeneous chains things are different, you have to handle the order of an address carefully when composing calldata, making a rpc call or prepare data targeting to evm chain, in this case any of the address parameters provided can be wrong. Apparently, if one prepare calldata from evm chain, for the same address variable, either all the references are correct, or all the references are incorrect, the latter one shall never happen, cause in evm chains it is hard to imagine why one would like to reverse addresses partially(e.g., keep toAddress and reverse the same variable as receiver). From this point of view, the check "if data comes from evm chains, then the check will be applied" is not that worthy adding, if contract itself is secure, it is better to reduce gas consumption in order to lower the possibility of destination chain tx delay(also there are other factors).

Paragraphs are not well organized, hope it doesn't cause misunderstanding.

**Comment by rvnlord** [comment]
That's why I keep asking, do you only utilize poly network or are you the authors of it as well? Because if the second one is true you can just make poly network always send the encoded data with some sort of flag or even a custom checksum - by default, without a possibility to compose fake data and regardless of the chain. All nodes would have the same logic (that is only if you are original devs of poly network core, I am not an idiot, I know you need all peers to update their software and reach consensus for that). But if you don't want to modify contracts that is the only other thing to do because as it stands it requires only one relayer to have a misconfigured node - there are no guarantees that the transaction is going to be relayed by your own properly configured node.

That's why I am also asking what configuration exactly did you change? because fake data was the direct result of the configuration being incorrect. Can a random peer indeed misconfigure their poly network node in the same way? If yes then you have to implement some kind of a safeguard in the contracts.

You just spent two paragraphs discussing my example approach which was just that - an example. In my last post I didn't even say to check equality anymore at all but to check the checksum of both, to revert the call (terminate the transaction) if any of them are not valid ethereum addresses. I said that precisely because of your example cases and because you don't want to modify the calldata in the contract. But I hear you if the destination is a non-EVM chain then you would have to modify the Neo3 contract for instance as well. 

To reiterate with your requirements and clarifications I don't want to modify any data at all anymore, just validate it (but not against one another). Both in EVM and non-EVM chain contracts (or alternatively if you are poly network core creators, modify the poly network code instead to enforce it to compose the transaction for destination chain correctly in all cases regardless of configuration). Even if you terminated the destination chain transaction due to misconfiguration using contract safeguards the money would at least be at the contract address and not at an address without known private key.
